# TensorFlow Basics

Remember to reference the video for full explanations, this is just a notebook for code reference.

You can import the library:

In [2]:
%pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
     -------------------------------------- 272.8/272.8 MB 1.0 MB/s eta 0:00:00
     -------------------------------------- 57.5/57.5 kB 507.9 kB/s eta 0:00:00
     ---------------------------------------- 1.7/1.7 MB 575.8 kB/s eta 0:00:00
     ------------------------------------ 422.5/422.5 kB 196.9 kB/s eta 0:00:00
     -------------------------------------- 65.5/65.5 kB 394.6 kB/s eta 0:00:00
     ---------------------------------------- 24.4/24.4 MB 1.5 MB/s eta 0:00:00
     ---------------------------------------- 1.3/1.3 MB 341.6 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
     ---------------------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.6.0 requires daal==2021.4.0, which is not installed.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.23.5 which is incompatible.


In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.12.0


### Simple Constants

Let's show how to create a simple constant with Tensorflow, which TF stores as a tensor object:

In [5]:
hello = tf.constant('Hello World')

In [6]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [7]:
x = tf.constant(100)

In [8]:
type(x)

tensorflow.python.framework.ops.EagerTensor

### Running Sessions

Now you can create a TensorFlow Session, which is a class for running TensorFlow operations.

A `Session` object encapsulates the environment in which `Operation`
objects are executed, and `Tensor` objects are evaluated. For example:

In [10]:
sess = tf.Session()

AttributeError: module 'tensorflow' has no attribute 'Session'

In [11]:
sess.run(hello)

NameError: name 'sess' is not defined

In [12]:
type(sess.run(hello))

NameError: name 'sess' is not defined

In [13]:
sess.run(x)

NameError: name 'sess' is not defined

In [14]:
type(sess.run(x))

NameError: name 'sess' is not defined

## Operations

You can line up multiple Tensorflow operations in to be run during a session:

In [15]:
x = tf.constant(2)
y = tf.constant(3)

In [16]:
with tf.Session() as sess:
    print('Operations with Constants')
    print('Addition',sess.run(x+y))
    print('Subtraction',sess.run(x-y))
    print('Multiplication',sess.run(x*y))
    print('Division',sess.run(x/y))

AttributeError: module 'tensorflow' has no attribute 'Session'

### Placeholder

You may not always have the constants right away, and you may be waiting for a constant to appear after a cycle of operations. **tf.placeholder** is a tool for this. It inserts a placeholder for a tensor that will be always fed.

**Important**: This tensor will produce an error if evaluated. Its value must be fed using the `feed_dict` optional argument to `Session.run()`,
`Tensor.eval()`, or `Operation.run()`. For example, for a placeholder of a matrix of floating point numbers:

    x = tf.placeholder(tf.float32, shape=(1024, 1024))

Here is an example for integer placeholders:

In [17]:
x = tf.placeholder(tf.int32)
y = tf.placeholder(tf.int32)

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [18]:
x

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [19]:
type(x)

tensorflow.python.framework.ops.EagerTensor

### Defining Operations

In [20]:
add = tf.add(x,y)
sub = tf.subtract(x,y)
mul = tf.multiply(x,y)

Running operations with variable input:

In [21]:
d = {x:20,y:30}

TypeError: Tensor is unhashable. Instead, use tensor.ref() as the key.

In [22]:
with tf.Session() as sess:
    print('Operations with Constants')
    print('Addition',sess.run(add,feed_dict=d))
    print('Subtraction',sess.run(sub,feed_dict=d))
    print('Multiplication',sess.run(mul,feed_dict=d))

AttributeError: module 'tensorflow' has no attribute 'Session'

Now let's see an example of a more complex operation, using Matrix Multiplication. First we need to create the matrices:

In [23]:
import numpy as np
# Make sure to use floats here, int64 will cause an error.
a = np.array([[5.0,5.0]])
b = np.array([[2.0],[2.0]])

In [24]:
a

array([[5., 5.]])

In [25]:
a.shape

(1, 2)

In [26]:
b

array([[2.],
       [2.]])

In [27]:
b.shape

(2, 1)

In [28]:
mat1 = tf.constant(a)

In [29]:
mat2 = tf.constant(b)

The matrix multiplication operation:

In [30]:
matrix_multi = tf.matmul(mat1,mat2)

Now run the session to perform the Operation:

In [31]:
with tf.Session() as sess:
    result = sess.run(matrix_multi)
    print(result)

AttributeError: module 'tensorflow' has no attribute 'Session'

That is all for now! Next we will expand these basic concepts to construct out own Multi-Layer Perceptron model!